# Generated by Django 2.1.1 on 2018-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.CharField(default='https://images.gr-assets.com/books/1388190055l/10048834.jpg', max_length=1000),
        ),
    ]
