# Generated by Django 2.1.7 on 2019-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190506_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Science Fiction', 'Science Fiction'), ('Biography', 'Biography'), ('Classics', 'Classics'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance')], default='Fantasy', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('SP', 'Spanish'), ('FR', 'French'), ('CH', 'Chinese'), ('JP', 'Japanese'), ('KN', 'Korean'), ('AR', 'Arabic')], default='EN', max_length=2),
        ),
    ]
