# Generated by Django 2.1.1 on 2018-12-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181130_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Miami', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='FL', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
